global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "bookstore-api"
    static_configs:
      - targets: ["bookstore-api:4001"]

  - job_name: "auth-api"
    static_configs:
      - targets: ["auth-api:4002"]

  - job_name: "gateway"
    static_configs:
      - targets: ["readify-gateway:8080"]
